image:
  repository: bitnamilegacy/kafka

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

controller:
  replicaCount: 3
  controllerOnly: false
  resourcesPreset: large

  persistence:
    enabled: false
  logPersistence:
    enabled: false

broker:
  replicaCount: 0

service:
  type: ClusterIP

externalAccess:
  enabled: false

networkPolicy:
  enabled: false

overrideConfiguration:
  auto.create.topics.enable: "true"

  offsets.topic.replication.factor: 3
  transaction.state.log.replication.factor: 3
  transaction.state.log.min.isr: 2
  default.replication.factor: 3
  min.insync.replicas: 2
  num.partitions: 3
