apiVersion: v1
kind: Service
metadata:
  name: oxia
  labels:
    name: oxia
spec:
  ports:
    - port: 6648
  clusterIP: None
  selector:
    role: oxia
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxia
spec:
  selector:
    matchLabels:
      role: oxia
  serviceName: "oxia"
  replicas: 1
  template:
    metadata:
      labels:
        role: oxia
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: oxia
          image: streamnative/oxia:main
          command:
            - oxia
            - standalone
          ports:
            - containerPort: 6648